/* automatically generated by rust-bindgen 0.69.4 */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __TIMESIZE: u32 = 64;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const __GLIBC_USE_C2X_STRTOL: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 39;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const _BITS_STDINT_LEAST_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const RKNN_FLAG_PRIOR_HIGH: u32 = 0;
pub const RKNN_FLAG_PRIOR_MEDIUM: u32 = 1;
pub const RKNN_FLAG_PRIOR_LOW: u32 = 2;
pub const RKNN_FLAG_ASYNC_MASK: u32 = 4;
pub const RKNN_FLAG_COLLECT_PERF_MASK: u32 = 8;
pub const RKNN_FLAG_MEM_ALLOC_OUTSIDE: u32 = 16;
pub const RKNN_FLAG_SHARE_WEIGHT_MEM: u32 = 32;
pub const RKNN_FLAG_FENCE_IN_OUTSIDE: u32 = 64;
pub const RKNN_FLAG_FENCE_OUT_OUTSIDE: u32 = 128;
pub const RKNN_FLAG_COLLECT_MODEL_INFO_ONLY: u32 = 256;
pub const RKNN_FLAG_INTERNAL_ALLOC_OUTSIDE: u32 = 512;
pub const RKNN_FLAG_EXECUTE_FALLBACK_PRIOR_DEVICE_GPU: u32 = 1024;
pub const RKNN_FLAG_ENABLE_SRAM: u32 = 2048;
pub const RKNN_FLAG_SHARE_SRAM: u32 = 4096;
pub const RKNN_FLAG_DISABLE_PROC_HIGH_PRIORITY: u32 = 8192;
pub const RKNN_FLAG_DISABLE_FLUSH_INPUT_MEM_CACHE: u32 = 16384;
pub const RKNN_FLAG_DISABLE_FLUSH_OUTPUT_MEM_CACHE: u32 = 32768;
pub const RKNN_SUCC: u32 = 0;
pub const RKNN_ERR_FAIL: i32 = -1;
pub const RKNN_ERR_TIMEOUT: i32 = -2;
pub const RKNN_ERR_DEVICE_UNAVAILABLE: i32 = -3;
pub const RKNN_ERR_MALLOC_FAIL: i32 = -4;
pub const RKNN_ERR_PARAM_INVALID: i32 = -5;
pub const RKNN_ERR_MODEL_INVALID: i32 = -6;
pub const RKNN_ERR_CTX_INVALID: i32 = -7;
pub const RKNN_ERR_INPUT_INVALID: i32 = -8;
pub const RKNN_ERR_OUTPUT_INVALID: i32 = -9;
pub const RKNN_ERR_DEVICE_UNMATCH: i32 = -10;
pub const RKNN_ERR_INCOMPATILE_PRE_COMPILE_MODEL: i32 = -11;
pub const RKNN_ERR_INCOMPATILE_OPTIMIZATION_LEVEL_VERSION: i32 = -12;
pub const RKNN_ERR_TARGET_PLATFORM_UNMATCH: i32 = -13;
pub const RKNN_MAX_DIMS: u32 = 16;
pub const RKNN_MAX_NUM_CHANNEL: u32 = 15;
pub const RKNN_MAX_NAME_LEN: u32 = 256;
pub const RKNN_MAX_DYNAMIC_SHAPE_NUM: u32 = 512;
pub const RKNN_WARNING_SKIP_CUSTOM_OP_COMPUTE: i32 = -14;
pub const RKNN_CUSTOM_OP_MAX_STR_LEN: u32 = 64;
pub const RKNN_CUSTOM_OP_MAX_VALUE_LEN: u32 = 32;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___fsid_t() {
    const UNINIT: ::std::mem::MaybeUninit<__fsid_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<__fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__fsid_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__fsid_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).__val) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__fsid_t),
            "::",
            stringify!(__val)
        )
    );
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub type rknn_context = u64;
pub const _rknn_query_cmd_RKNN_QUERY_IN_OUT_NUM: _rknn_query_cmd = 0;
pub const _rknn_query_cmd_RKNN_QUERY_INPUT_ATTR: _rknn_query_cmd = 1;
pub const _rknn_query_cmd_RKNN_QUERY_OUTPUT_ATTR: _rknn_query_cmd = 2;
pub const _rknn_query_cmd_RKNN_QUERY_PERF_DETAIL: _rknn_query_cmd = 3;
pub const _rknn_query_cmd_RKNN_QUERY_PERF_RUN: _rknn_query_cmd = 4;
pub const _rknn_query_cmd_RKNN_QUERY_SDK_VERSION: _rknn_query_cmd = 5;
pub const _rknn_query_cmd_RKNN_QUERY_MEM_SIZE: _rknn_query_cmd = 6;
pub const _rknn_query_cmd_RKNN_QUERY_CUSTOM_STRING: _rknn_query_cmd = 7;
pub const _rknn_query_cmd_RKNN_QUERY_NATIVE_INPUT_ATTR: _rknn_query_cmd = 8;
pub const _rknn_query_cmd_RKNN_QUERY_NATIVE_OUTPUT_ATTR: _rknn_query_cmd = 9;
pub const _rknn_query_cmd_RKNN_QUERY_NATIVE_NC1HWC2_INPUT_ATTR: _rknn_query_cmd = 8;
pub const _rknn_query_cmd_RKNN_QUERY_NATIVE_NC1HWC2_OUTPUT_ATTR: _rknn_query_cmd = 9;
pub const _rknn_query_cmd_RKNN_QUERY_NATIVE_NHWC_INPUT_ATTR: _rknn_query_cmd = 10;
pub const _rknn_query_cmd_RKNN_QUERY_NATIVE_NHWC_OUTPUT_ATTR: _rknn_query_cmd = 11;
pub const _rknn_query_cmd_RKNN_QUERY_DEVICE_MEM_INFO: _rknn_query_cmd = 12;
pub const _rknn_query_cmd_RKNN_QUERY_INPUT_DYNAMIC_RANGE: _rknn_query_cmd = 13;
pub const _rknn_query_cmd_RKNN_QUERY_CURRENT_INPUT_ATTR: _rknn_query_cmd = 14;
pub const _rknn_query_cmd_RKNN_QUERY_CURRENT_OUTPUT_ATTR: _rknn_query_cmd = 15;
pub const _rknn_query_cmd_RKNN_QUERY_CURRENT_NATIVE_INPUT_ATTR: _rknn_query_cmd = 16;
pub const _rknn_query_cmd_RKNN_QUERY_CURRENT_NATIVE_OUTPUT_ATTR: _rknn_query_cmd = 17;
pub const _rknn_query_cmd_RKNN_QUERY_CMD_MAX: _rknn_query_cmd = 18;
pub type _rknn_query_cmd = ::std::os::raw::c_uint;
pub use self::_rknn_query_cmd as rknn_query_cmd;
pub const _rknn_tensor_type_RKNN_TENSOR_FLOAT32: _rknn_tensor_type = 0;
pub const _rknn_tensor_type_RKNN_TENSOR_FLOAT16: _rknn_tensor_type = 1;
pub const _rknn_tensor_type_RKNN_TENSOR_INT8: _rknn_tensor_type = 2;
pub const _rknn_tensor_type_RKNN_TENSOR_UINT8: _rknn_tensor_type = 3;
pub const _rknn_tensor_type_RKNN_TENSOR_INT16: _rknn_tensor_type = 4;
pub const _rknn_tensor_type_RKNN_TENSOR_UINT16: _rknn_tensor_type = 5;
pub const _rknn_tensor_type_RKNN_TENSOR_INT32: _rknn_tensor_type = 6;
pub const _rknn_tensor_type_RKNN_TENSOR_UINT32: _rknn_tensor_type = 7;
pub const _rknn_tensor_type_RKNN_TENSOR_INT64: _rknn_tensor_type = 8;
pub const _rknn_tensor_type_RKNN_TENSOR_BOOL: _rknn_tensor_type = 9;
pub const _rknn_tensor_type_RKNN_TENSOR_INT4: _rknn_tensor_type = 10;
pub const _rknn_tensor_type_RKNN_TENSOR_TYPE_MAX: _rknn_tensor_type = 11;
pub type _rknn_tensor_type = ::std::os::raw::c_uint;
pub use self::_rknn_tensor_type as rknn_tensor_type;
pub const _rknn_tensor_qnt_type_RKNN_TENSOR_QNT_NONE: _rknn_tensor_qnt_type = 0;
pub const _rknn_tensor_qnt_type_RKNN_TENSOR_QNT_DFP: _rknn_tensor_qnt_type = 1;
pub const _rknn_tensor_qnt_type_RKNN_TENSOR_QNT_AFFINE_ASYMMETRIC: _rknn_tensor_qnt_type = 2;
pub const _rknn_tensor_qnt_type_RKNN_TENSOR_QNT_MAX: _rknn_tensor_qnt_type = 3;
pub type _rknn_tensor_qnt_type = ::std::os::raw::c_uint;
pub use self::_rknn_tensor_qnt_type as rknn_tensor_qnt_type;
pub const _rknn_tensor_format_RKNN_TENSOR_NCHW: _rknn_tensor_format = 0;
pub const _rknn_tensor_format_RKNN_TENSOR_NHWC: _rknn_tensor_format = 1;
pub const _rknn_tensor_format_RKNN_TENSOR_NC1HWC2: _rknn_tensor_format = 2;
pub const _rknn_tensor_format_RKNN_TENSOR_UNDEFINED: _rknn_tensor_format = 3;
pub const _rknn_tensor_format_RKNN_TENSOR_FORMAT_MAX: _rknn_tensor_format = 4;
pub type _rknn_tensor_format = ::std::os::raw::c_uint;
pub use self::_rknn_tensor_format as rknn_tensor_format;
pub const _rknn_core_mask_RKNN_NPU_CORE_AUTO: _rknn_core_mask = 0;
pub const _rknn_core_mask_RKNN_NPU_CORE_0: _rknn_core_mask = 1;
pub const _rknn_core_mask_RKNN_NPU_CORE_1: _rknn_core_mask = 2;
pub const _rknn_core_mask_RKNN_NPU_CORE_2: _rknn_core_mask = 4;
pub const _rknn_core_mask_RKNN_NPU_CORE_0_1: _rknn_core_mask = 3;
pub const _rknn_core_mask_RKNN_NPU_CORE_0_1_2: _rknn_core_mask = 7;
pub const _rknn_core_mask_RKNN_NPU_CORE_ALL: _rknn_core_mask = 65535;
pub const _rknn_core_mask_RKNN_NPU_CORE_UNDEFINED: _rknn_core_mask = 65536;
pub type _rknn_core_mask = ::std::os::raw::c_uint;
pub use self::_rknn_core_mask as rknn_core_mask;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_input_output_num {
    pub n_input: u32,
    pub n_output: u32,
}
#[test]
fn bindgen_test_layout__rknn_input_output_num() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_input_output_num> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_input_output_num>(),
        8usize,
        concat!("Size of: ", stringify!(_rknn_input_output_num))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_input_output_num>(),
        4usize,
        concat!("Alignment of ", stringify!(_rknn_input_output_num))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_input) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input_output_num),
            "::",
            stringify!(n_input)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_output) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input_output_num),
            "::",
            stringify!(n_output)
        )
    );
}
pub type rknn_input_output_num = _rknn_input_output_num;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_tensor_attr {
    pub index: u32,
    pub n_dims: u32,
    pub dims: [u32; 16usize],
    pub name: [::std::os::raw::c_char; 256usize],
    pub n_elems: u32,
    pub size: u32,
    pub fmt: rknn_tensor_format,
    pub type_: rknn_tensor_type,
    pub qnt_type: rknn_tensor_qnt_type,
    pub fl: i8,
    pub zp: i32,
    pub scale: f32,
    pub w_stride: u32,
    pub size_with_stride: u32,
    pub pass_through: u8,
    pub h_stride: u32,
}
#[test]
fn bindgen_test_layout__rknn_tensor_attr() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_tensor_attr> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_tensor_attr>(),
        376usize,
        concat!("Size of: ", stringify!(_rknn_tensor_attr))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_tensor_attr>(),
        4usize,
        concat!("Alignment of ", stringify!(_rknn_tensor_attr))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_dims) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(n_dims)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).dims) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(dims)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_elems) as usize - ptr as usize },
        328usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(n_elems)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        332usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fmt) as usize - ptr as usize },
        336usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(fmt)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        340usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).qnt_type) as usize - ptr as usize },
        344usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(qnt_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fl) as usize - ptr as usize },
        348usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(fl)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).zp) as usize - ptr as usize },
        352usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(zp)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).scale) as usize - ptr as usize },
        356usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(scale)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).w_stride) as usize - ptr as usize },
        360usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(w_stride)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).size_with_stride) as usize - ptr as usize },
        364usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(size_with_stride)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pass_through) as usize - ptr as usize },
        368usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(pass_through)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).h_stride) as usize - ptr as usize },
        372usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_attr),
            "::",
            stringify!(h_stride)
        )
    );
}
pub type rknn_tensor_attr = _rknn_tensor_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_input_range {
    pub index: u32,
    pub shape_number: u32,
    pub fmt: rknn_tensor_format,
    pub name: [::std::os::raw::c_char; 256usize],
    pub dyn_range: [[u32; 16usize]; 512usize],
    pub n_dims: u32,
}
#[test]
fn bindgen_test_layout__rknn_input_range() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_input_range> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_input_range>(),
        33040usize,
        concat!("Size of: ", stringify!(_rknn_input_range))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_input_range>(),
        4usize,
        concat!("Alignment of ", stringify!(_rknn_input_range))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input_range),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).shape_number) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input_range),
            "::",
            stringify!(shape_number)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fmt) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input_range),
            "::",
            stringify!(fmt)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input_range),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).dyn_range) as usize - ptr as usize },
        268usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input_range),
            "::",
            stringify!(dyn_range)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_dims) as usize - ptr as usize },
        33036usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input_range),
            "::",
            stringify!(n_dims)
        )
    );
}
pub type rknn_input_range = _rknn_input_range;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_perf_detail {
    pub perf_data: *mut ::std::os::raw::c_char,
    pub data_len: u64,
}
#[test]
fn bindgen_test_layout__rknn_perf_detail() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_perf_detail> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_perf_detail>(),
        16usize,
        concat!("Size of: ", stringify!(_rknn_perf_detail))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_perf_detail>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_perf_detail))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).perf_data) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_perf_detail),
            "::",
            stringify!(perf_data)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).data_len) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_perf_detail),
            "::",
            stringify!(data_len)
        )
    );
}
pub type rknn_perf_detail = _rknn_perf_detail;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_perf_run {
    pub run_duration: i64,
}
#[test]
fn bindgen_test_layout__rknn_perf_run() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_perf_run> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_perf_run>(),
        8usize,
        concat!("Size of: ", stringify!(_rknn_perf_run))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_perf_run>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_perf_run))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).run_duration) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_perf_run),
            "::",
            stringify!(run_duration)
        )
    );
}
pub type rknn_perf_run = _rknn_perf_run;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_sdk_version {
    pub api_version: [::std::os::raw::c_char; 256usize],
    pub drv_version: [::std::os::raw::c_char; 256usize],
}
#[test]
fn bindgen_test_layout__rknn_sdk_version() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_sdk_version> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_sdk_version>(),
        512usize,
        concat!("Size of: ", stringify!(_rknn_sdk_version))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_sdk_version>(),
        1usize,
        concat!("Alignment of ", stringify!(_rknn_sdk_version))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).api_version) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_sdk_version),
            "::",
            stringify!(api_version)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).drv_version) as usize - ptr as usize },
        256usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_sdk_version),
            "::",
            stringify!(drv_version)
        )
    );
}
pub type rknn_sdk_version = _rknn_sdk_version;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_mem_size {
    pub total_weight_size: u32,
    pub total_internal_size: u32,
    pub total_dma_allocated_size: u64,
    pub total_sram_size: u32,
    pub free_sram_size: u32,
    pub reserved: [u32; 10usize],
}
#[test]
fn bindgen_test_layout__rknn_mem_size() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_mem_size> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_mem_size>(),
        64usize,
        concat!("Size of: ", stringify!(_rknn_mem_size))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_mem_size>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_mem_size))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).total_weight_size) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_mem_size),
            "::",
            stringify!(total_weight_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).total_internal_size) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_mem_size),
            "::",
            stringify!(total_internal_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).total_dma_allocated_size) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_mem_size),
            "::",
            stringify!(total_dma_allocated_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).total_sram_size) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_mem_size),
            "::",
            stringify!(total_sram_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).free_sram_size) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_mem_size),
            "::",
            stringify!(free_sram_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_mem_size),
            "::",
            stringify!(reserved)
        )
    );
}
pub type rknn_mem_size = _rknn_mem_size;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_custom_string {
    pub string: [::std::os::raw::c_char; 1024usize],
}
#[test]
fn bindgen_test_layout__rknn_custom_string() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_custom_string> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_custom_string>(),
        1024usize,
        concat!("Size of: ", stringify!(_rknn_custom_string))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_custom_string>(),
        1usize,
        concat!("Alignment of ", stringify!(_rknn_custom_string))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).string) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_string),
            "::",
            stringify!(string)
        )
    );
}
pub type rknn_custom_string = _rknn_custom_string;
pub const _rknn_tensor_mem_flags_RKNN_TENSOR_MEMORY_FLAGS_ALLOC_INSIDE: _rknn_tensor_mem_flags = 1;
pub const _rknn_tensor_mem_flags_RKNN_TENSOR_MEMORY_FLAGS_FROM_FD: _rknn_tensor_mem_flags = 2;
pub const _rknn_tensor_mem_flags_RKNN_TENSOR_MEMORY_FLAGS_FROM_PHYS: _rknn_tensor_mem_flags = 3;
pub const _rknn_tensor_mem_flags_RKNN_TENSOR_MEMORY_FLAGS_UNKNOWN: _rknn_tensor_mem_flags = 4;
pub type _rknn_tensor_mem_flags = ::std::os::raw::c_uint;
pub use self::_rknn_tensor_mem_flags as rknn_tensor_mem_flags;
pub const _rknn_mem_alloc_flags_RKNN_FLAG_MEMORY_FLAGS_DEFAULT: _rknn_mem_alloc_flags = 0;
pub const _rknn_mem_alloc_flags_RKNN_FLAG_MEMORY_CACHEABLE: _rknn_mem_alloc_flags = 1;
pub const _rknn_mem_alloc_flags_RKNN_FLAG_MEMORY_NON_CACHEABLE: _rknn_mem_alloc_flags = 2;
pub type _rknn_mem_alloc_flags = ::std::os::raw::c_uint;
pub use self::_rknn_mem_alloc_flags as rknn_mem_alloc_flags;
pub const _rknn_mem_sync_mode_RKNN_MEMORY_SYNC_TO_DEVICE: _rknn_mem_sync_mode = 1;
pub const _rknn_mem_sync_mode_RKNN_MEMORY_SYNC_FROM_DEVICE: _rknn_mem_sync_mode = 2;
pub const _rknn_mem_sync_mode_RKNN_MEMORY_SYNC_BIDIRECTIONAL: _rknn_mem_sync_mode = 3;
pub type _rknn_mem_sync_mode = ::std::os::raw::c_uint;
pub use self::_rknn_mem_sync_mode as rknn_mem_sync_mode;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_tensor_memory {
    pub virt_addr: *mut ::std::os::raw::c_void,
    pub phys_addr: u64,
    pub fd: i32,
    pub offset: i32,
    pub size: u32,
    pub flags: u32,
    pub priv_data: *mut ::std::os::raw::c_void,
}
#[test]
fn bindgen_test_layout__rknn_tensor_memory() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_tensor_memory> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_tensor_memory>(),
        40usize,
        concat!("Size of: ", stringify!(_rknn_tensor_memory))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_tensor_memory>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_tensor_memory))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).virt_addr) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_memory),
            "::",
            stringify!(virt_addr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).phys_addr) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_memory),
            "::",
            stringify!(phys_addr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fd) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_memory),
            "::",
            stringify!(fd)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).offset) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_memory),
            "::",
            stringify!(offset)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_memory),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).flags) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_memory),
            "::",
            stringify!(flags)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).priv_data) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_tensor_memory),
            "::",
            stringify!(priv_data)
        )
    );
}
pub type rknn_tensor_mem = _rknn_tensor_memory;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_input {
    pub index: u32,
    pub buf: *mut ::std::os::raw::c_void,
    pub size: u32,
    pub pass_through: u8,
    pub type_: rknn_tensor_type,
    pub fmt: rknn_tensor_format,
}
#[test]
fn bindgen_test_layout__rknn_input() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_input> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_input>(),
        32usize,
        concat!("Size of: ", stringify!(_rknn_input))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_input>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_input))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).buf) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input),
            "::",
            stringify!(buf)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).pass_through) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input),
            "::",
            stringify!(pass_through)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fmt) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_input),
            "::",
            stringify!(fmt)
        )
    );
}
pub type rknn_input = _rknn_input;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_output {
    pub want_float: u8,
    pub is_prealloc: u8,
    pub index: u32,
    pub buf: *mut ::std::os::raw::c_void,
    pub size: u32,
}
#[test]
fn bindgen_test_layout__rknn_output() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_output> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_output>(),
        24usize,
        concat!("Size of: ", stringify!(_rknn_output))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_output>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_output))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).want_float) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_output),
            "::",
            stringify!(want_float)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).is_prealloc) as usize - ptr as usize },
        1usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_output),
            "::",
            stringify!(is_prealloc)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).index) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_output),
            "::",
            stringify!(index)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).buf) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_output),
            "::",
            stringify!(buf)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_output),
            "::",
            stringify!(size)
        )
    );
}
pub type rknn_output = _rknn_output;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_init_extend {
    pub ctx: rknn_context,
    pub real_model_offset: i32,
    pub real_model_size: u32,
    pub reserved: [u8; 120usize],
}
#[test]
fn bindgen_test_layout__rknn_init_extend() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_init_extend> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_init_extend>(),
        136usize,
        concat!("Size of: ", stringify!(_rknn_init_extend))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_init_extend>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_init_extend))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).ctx) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_init_extend),
            "::",
            stringify!(ctx)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).real_model_offset) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_init_extend),
            "::",
            stringify!(real_model_offset)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).real_model_size) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_init_extend),
            "::",
            stringify!(real_model_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_init_extend),
            "::",
            stringify!(reserved)
        )
    );
}
pub type rknn_init_extend = _rknn_init_extend;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_run_extend {
    pub frame_id: u64,
    pub non_block: i32,
    pub timeout_ms: i32,
    pub fence_fd: i32,
}
#[test]
fn bindgen_test_layout__rknn_run_extend() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_run_extend> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_run_extend>(),
        24usize,
        concat!("Size of: ", stringify!(_rknn_run_extend))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_run_extend>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_run_extend))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).frame_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_run_extend),
            "::",
            stringify!(frame_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).non_block) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_run_extend),
            "::",
            stringify!(non_block)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).timeout_ms) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_run_extend),
            "::",
            stringify!(timeout_ms)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).fence_fd) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_run_extend),
            "::",
            stringify!(fence_fd)
        )
    );
}
pub type rknn_run_extend = _rknn_run_extend;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_output_extend {
    pub frame_id: u64,
}
#[test]
fn bindgen_test_layout__rknn_output_extend() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_output_extend> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_output_extend>(),
        8usize,
        concat!("Size of: ", stringify!(_rknn_output_extend))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_output_extend>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_output_extend))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).frame_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_output_extend),
            "::",
            stringify!(frame_id)
        )
    );
}
pub type rknn_output_extend = _rknn_output_extend;
extern "C" {
    pub fn rknn_init(
        context: *mut rknn_context,
        model: *mut ::std::os::raw::c_void,
        size: u32,
        flag: u32,
        extend: *mut rknn_init_extend,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_dup_context(
        context_in: *mut rknn_context,
        context_out: *mut rknn_context,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_destroy(context: rknn_context) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_query(
        context: rknn_context,
        cmd: rknn_query_cmd,
        info: *mut ::std::os::raw::c_void,
        size: u32,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_inputs_set(
        context: rknn_context,
        n_inputs: u32,
        inputs: *mut rknn_input,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_set_batch_core_num(
        context: rknn_context,
        core_num: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_set_core_mask(
        context: rknn_context,
        core_mask: rknn_core_mask,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_run(context: rknn_context, extend: *mut rknn_run_extend) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_wait(context: rknn_context, extend: *mut rknn_run_extend) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_outputs_get(
        context: rknn_context,
        n_outputs: u32,
        outputs: *mut rknn_output,
        extend: *mut rknn_output_extend,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_outputs_release(
        context: rknn_context,
        n_ouputs: u32,
        outputs: *mut rknn_output,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_create_mem_from_phys(
        ctx: rknn_context,
        phys_addr: u64,
        virt_addr: *mut ::std::os::raw::c_void,
        size: u32,
    ) -> *mut rknn_tensor_mem;
}
extern "C" {
    pub fn rknn_create_mem_from_fd(
        ctx: rknn_context,
        fd: i32,
        virt_addr: *mut ::std::os::raw::c_void,
        size: u32,
        offset: i32,
    ) -> *mut rknn_tensor_mem;
}
extern "C" {
    pub fn rknn_create_mem_from_mb_blk(
        ctx: rknn_context,
        mb_blk: *mut ::std::os::raw::c_void,
        offset: i32,
    ) -> *mut rknn_tensor_mem;
}
extern "C" {
    pub fn rknn_create_mem(ctx: rknn_context, size: u32) -> *mut rknn_tensor_mem;
}
extern "C" {
    pub fn rknn_create_mem2(ctx: rknn_context, size: u64, alloc_flags: u64)
        -> *mut rknn_tensor_mem;
}
extern "C" {
    pub fn rknn_destroy_mem(ctx: rknn_context, mem: *mut rknn_tensor_mem) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_set_weight_mem(
        ctx: rknn_context,
        mem: *mut rknn_tensor_mem,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_set_internal_mem(
        ctx: rknn_context,
        mem: *mut rknn_tensor_mem,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_set_io_mem(
        ctx: rknn_context,
        mem: *mut rknn_tensor_mem,
        attr: *mut rknn_tensor_attr,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_set_input_shape(
        ctx: rknn_context,
        attr: *mut rknn_tensor_attr,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_set_input_shapes(
        ctx: rknn_context,
        n_inputs: u32,
        attr: *mut rknn_tensor_attr,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_mem_sync(
        context: rknn_context,
        mem: *mut rknn_tensor_mem,
        mode: rknn_mem_sync_mode,
    ) -> ::std::os::raw::c_int;
}
pub type rknn_custom_op_interal_context = u64;
pub const _rknn_target_type_RKNN_TARGET_TYPE_CPU: _rknn_target_type = 1;
pub const _rknn_target_type_RKNN_TARGET_TYPE_GPU: _rknn_target_type = 2;
pub const _rknn_target_type_RKNN_TARGET_TYPE_MAX: _rknn_target_type = 3;
pub type _rknn_target_type = ::std::os::raw::c_uint;
pub use self::_rknn_target_type as rknn_target_type;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_gpu_op_context {
    pub cl_context: *mut ::std::os::raw::c_void,
    pub cl_command_queue: *mut ::std::os::raw::c_void,
    pub cl_kernel: *mut ::std::os::raw::c_void,
}
#[test]
fn bindgen_test_layout__rknn_gpu_op_context() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_gpu_op_context> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_gpu_op_context>(),
        24usize,
        concat!("Size of: ", stringify!(_rknn_gpu_op_context))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_gpu_op_context>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_gpu_op_context))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cl_context) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_gpu_op_context),
            "::",
            stringify!(cl_context)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cl_command_queue) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_gpu_op_context),
            "::",
            stringify!(cl_command_queue)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cl_kernel) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_gpu_op_context),
            "::",
            stringify!(cl_kernel)
        )
    );
}
pub type rknn_gpu_op_context = _rknn_gpu_op_context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_custom_op_context {
    pub target: rknn_target_type,
    pub internal_ctx: rknn_custom_op_interal_context,
    pub gpu_ctx: rknn_gpu_op_context,
    pub priv_data: *mut ::std::os::raw::c_void,
}
#[test]
fn bindgen_test_layout__rknn_custom_op_context() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_custom_op_context> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_custom_op_context>(),
        48usize,
        concat!("Size of: ", stringify!(_rknn_custom_op_context))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_custom_op_context>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_custom_op_context))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).target) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_context),
            "::",
            stringify!(target)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).internal_ctx) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_context),
            "::",
            stringify!(internal_ctx)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).gpu_ctx) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_context),
            "::",
            stringify!(gpu_ctx)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).priv_data) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_context),
            "::",
            stringify!(priv_data)
        )
    );
}
pub type rknn_custom_op_context = _rknn_custom_op_context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_custom_op_tensor {
    pub attr: rknn_tensor_attr,
    pub mem: rknn_tensor_mem,
}
#[test]
fn bindgen_test_layout__rknn_custom_op_tensor() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_custom_op_tensor> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_custom_op_tensor>(),
        416usize,
        concat!("Size of: ", stringify!(_rknn_custom_op_tensor))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_custom_op_tensor>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_custom_op_tensor))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).attr) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_tensor),
            "::",
            stringify!(attr)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mem) as usize - ptr as usize },
        376usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_tensor),
            "::",
            stringify!(mem)
        )
    );
}
pub type rknn_custom_op_tensor = _rknn_custom_op_tensor;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_custom_op_attr {
    pub name: [::std::os::raw::c_char; 256usize],
    pub dtype: rknn_tensor_type,
    pub n_elems: u32,
    pub data: *mut ::std::os::raw::c_void,
}
#[test]
fn bindgen_test_layout__rknn_custom_op_attr() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_custom_op_attr> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_custom_op_attr>(),
        272usize,
        concat!("Size of: ", stringify!(_rknn_custom_op_attr))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_custom_op_attr>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_custom_op_attr))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_attr),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).dtype) as usize - ptr as usize },
        256usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_attr),
            "::",
            stringify!(dtype)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_elems) as usize - ptr as usize },
        260usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_attr),
            "::",
            stringify!(n_elems)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).data) as usize - ptr as usize },
        264usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op_attr),
            "::",
            stringify!(data)
        )
    );
}
pub type rknn_custom_op_attr = _rknn_custom_op_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_custom_op {
    pub version: u32,
    pub target: rknn_target_type,
    pub op_type: [::std::os::raw::c_char; 256usize],
    pub cl_kernel_name: [::std::os::raw::c_char; 256usize],
    pub cl_kernel_source: *mut ::std::os::raw::c_char,
    pub cl_source_size: u64,
    pub cl_build_options: [::std::os::raw::c_char; 256usize],
    #[doc = " The callback function sets that the users need to code"]
    pub init: ::std::option::Option<
        unsafe extern "C" fn(
            op_ctx: *mut rknn_custom_op_context,
            inputs: *mut rknn_custom_op_tensor,
            n_inputs: u32,
            outputs: *mut rknn_custom_op_tensor,
            n_outputs: u32,
        ) -> ::std::os::raw::c_int,
    >,
    pub prepare: ::std::option::Option<
        unsafe extern "C" fn(
            op_ctx: *mut rknn_custom_op_context,
            inputs: *mut rknn_custom_op_tensor,
            n_inputs: u32,
            outputs: *mut rknn_custom_op_tensor,
            n_outputs: u32,
        ) -> ::std::os::raw::c_int,
    >,
    pub compute: ::std::option::Option<
        unsafe extern "C" fn(
            op_ctx: *mut rknn_custom_op_context,
            inputs: *mut rknn_custom_op_tensor,
            n_inputs: u32,
            outputs: *mut rknn_custom_op_tensor,
            n_outputs: u32,
        ) -> ::std::os::raw::c_int,
    >,
    pub compute_native: ::std::option::Option<
        unsafe extern "C" fn(
            op_ctx: *mut rknn_custom_op_context,
            inputs: *mut rknn_custom_op_tensor,
            n_inputs: u32,
            outputs: *mut rknn_custom_op_tensor,
            n_outputs: u32,
        ) -> ::std::os::raw::c_int,
    >,
    pub destroy: ::std::option::Option<
        unsafe extern "C" fn(op_ctx: *mut rknn_custom_op_context) -> ::std::os::raw::c_int,
    >,
}
#[test]
fn bindgen_test_layout__rknn_custom_op() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_custom_op> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_custom_op>(),
        832usize,
        concat!("Size of: ", stringify!(_rknn_custom_op))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_custom_op>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_custom_op))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).version) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(version)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).target) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(target)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).op_type) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(op_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cl_kernel_name) as usize - ptr as usize },
        264usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(cl_kernel_name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cl_kernel_source) as usize - ptr as usize },
        520usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(cl_kernel_source)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cl_source_size) as usize - ptr as usize },
        528usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(cl_source_size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cl_build_options) as usize - ptr as usize },
        536usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(cl_build_options)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).init) as usize - ptr as usize },
        792usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(init)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).prepare) as usize - ptr as usize },
        800usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(prepare)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).compute) as usize - ptr as usize },
        808usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(compute)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).compute_native) as usize - ptr as usize },
        816usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(compute_native)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).destroy) as usize - ptr as usize },
        824usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_custom_op),
            "::",
            stringify!(destroy)
        )
    );
}
pub type rknn_custom_op = _rknn_custom_op;
#[doc = " dlopen custom op with so required this function"]
pub type get_custom_op_func = ::std::option::Option<unsafe extern "C" fn() -> *mut rknn_custom_op>;
extern "C" {
    pub fn rknn_register_custom_ops(
        ctx: rknn_context,
        op: *mut rknn_custom_op,
        custom_op_num: u32,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_custom_op_get_op_attr(
        op_ctx: *mut rknn_custom_op_context,
        attr_name: *const ::std::os::raw::c_char,
        op_attr: *mut rknn_custom_op_attr,
    );
}
pub type rknn_matmul_ctx = rknn_context;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_quant_params {
    pub name: [::std::os::raw::c_char; 256usize],
    pub scale: *mut f32,
    pub scale_len: i32,
    pub zp: *mut i32,
    pub zp_len: i32,
}
#[test]
fn bindgen_test_layout__rknn_quant_params() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_quant_params> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_quant_params>(),
        288usize,
        concat!("Size of: ", stringify!(_rknn_quant_params))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_quant_params>(),
        8usize,
        concat!("Alignment of ", stringify!(_rknn_quant_params))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_quant_params),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).scale) as usize - ptr as usize },
        256usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_quant_params),
            "::",
            stringify!(scale)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).scale_len) as usize - ptr as usize },
        264usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_quant_params),
            "::",
            stringify!(scale_len)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).zp) as usize - ptr as usize },
        272usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_quant_params),
            "::",
            stringify!(zp)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).zp_len) as usize - ptr as usize },
        280usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_quant_params),
            "::",
            stringify!(zp_len)
        )
    );
}
pub type rknn_quant_params = _rknn_quant_params;
pub const _rknn_matmul_type_RKNN_FLOAT16_MM_FLOAT16_TO_FLOAT32: _rknn_matmul_type = 1;
pub const _rknn_matmul_type_RKNN_INT8_MM_INT8_TO_INT32: _rknn_matmul_type = 2;
pub const _rknn_matmul_type_RKNN_INT8_MM_INT8_TO_INT8: _rknn_matmul_type = 3;
pub const _rknn_matmul_type_RKNN_FLOAT16_MM_FLOAT16_TO_FLOAT16: _rknn_matmul_type = 4;
pub const _rknn_matmul_type_RKNN_FLOAT16_MM_INT8_TO_FLOAT32: _rknn_matmul_type = 5;
pub const _rknn_matmul_type_RKNN_FLOAT16_MM_INT8_TO_FLOAT16: _rknn_matmul_type = 6;
pub const _rknn_matmul_type_RKNN_FLOAT16_MM_INT4_TO_FLOAT32: _rknn_matmul_type = 7;
pub const _rknn_matmul_type_RKNN_FLOAT16_MM_INT4_TO_FLOAT16: _rknn_matmul_type = 8;
pub const _rknn_matmul_type_RKNN_INT4_MM_INT4_TO_INT16: _rknn_matmul_type = 10;
pub const _rknn_matmul_type_RKNN_INT8_MM_INT4_TO_INT32: _rknn_matmul_type = 11;
pub type _rknn_matmul_type = ::std::os::raw::c_uint;
pub use self::_rknn_matmul_type as rknn_matmul_type;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_matmul_tensor_attr {
    pub name: [::std::os::raw::c_char; 256usize],
    pub n_dims: u32,
    pub dims: [u32; 16usize],
    pub size: u32,
    pub type_: rknn_tensor_type,
}
#[test]
fn bindgen_test_layout__rknn_matmul_tensor_attr() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_matmul_tensor_attr> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_matmul_tensor_attr>(),
        332usize,
        concat!("Size of: ", stringify!(_rknn_matmul_tensor_attr))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_matmul_tensor_attr>(),
        4usize,
        concat!("Alignment of ", stringify!(_rknn_matmul_tensor_attr))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_tensor_attr),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_dims) as usize - ptr as usize },
        256usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_tensor_attr),
            "::",
            stringify!(n_dims)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).dims) as usize - ptr as usize },
        260usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_tensor_attr),
            "::",
            stringify!(dims)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).size) as usize - ptr as usize },
        324usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_tensor_attr),
            "::",
            stringify!(size)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        328usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_tensor_attr),
            "::",
            stringify!(type_)
        )
    );
}
pub type rknn_matmul_tensor_attr = _rknn_matmul_tensor_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_matmul_io_attr {
    pub A: rknn_matmul_tensor_attr,
    pub B: rknn_matmul_tensor_attr,
    pub C: rknn_matmul_tensor_attr,
}
#[test]
fn bindgen_test_layout__rknn_matmul_io_attr() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_matmul_io_attr> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_matmul_io_attr>(),
        996usize,
        concat!("Size of: ", stringify!(_rknn_matmul_io_attr))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_matmul_io_attr>(),
        4usize,
        concat!("Alignment of ", stringify!(_rknn_matmul_io_attr))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).A) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_io_attr),
            "::",
            stringify!(A)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).B) as usize - ptr as usize },
        332usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_io_attr),
            "::",
            stringify!(B)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).C) as usize - ptr as usize },
        664usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_io_attr),
            "::",
            stringify!(C)
        )
    );
}
pub type rknn_matmul_io_attr = _rknn_matmul_io_attr;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _rknn_matmul_shape {
    pub M: i32,
    pub K: i32,
    pub N: i32,
}
#[test]
fn bindgen_test_layout__rknn_matmul_shape() {
    const UNINIT: ::std::mem::MaybeUninit<_rknn_matmul_shape> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<_rknn_matmul_shape>(),
        12usize,
        concat!("Size of: ", stringify!(_rknn_matmul_shape))
    );
    assert_eq!(
        ::std::mem::align_of::<_rknn_matmul_shape>(),
        4usize,
        concat!("Alignment of ", stringify!(_rknn_matmul_shape))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).M) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_shape),
            "::",
            stringify!(M)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).K) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_shape),
            "::",
            stringify!(K)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).N) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(_rknn_matmul_shape),
            "::",
            stringify!(N)
        )
    );
}
pub type rknn_matmul_shape = _rknn_matmul_shape;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rknn_matmul_info_t {
    pub M: i32,
    pub K: i32,
    pub N: i32,
    pub type_: rknn_matmul_type,
    pub B_layout: i16,
    pub B_quant_type: i16,
    pub AC_layout: i16,
    pub AC_quant_type: i16,
    pub iommu_domain_id: i32,
    pub reserved: [i8; 36usize],
}
#[test]
fn bindgen_test_layout_rknn_matmul_info_t() {
    const UNINIT: ::std::mem::MaybeUninit<rknn_matmul_info_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<rknn_matmul_info_t>(),
        64usize,
        concat!("Size of: ", stringify!(rknn_matmul_info_t))
    );
    assert_eq!(
        ::std::mem::align_of::<rknn_matmul_info_t>(),
        4usize,
        concat!("Alignment of ", stringify!(rknn_matmul_info_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).M) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(M)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).K) as usize - ptr as usize },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(K)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).N) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(N)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).type_) as usize - ptr as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(type_)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).B_layout) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(B_layout)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).B_quant_type) as usize - ptr as usize },
        18usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(B_quant_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).AC_layout) as usize - ptr as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(AC_layout)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).AC_quant_type) as usize - ptr as usize },
        22usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(AC_quant_type)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).iommu_domain_id) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(iommu_domain_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).reserved) as usize - ptr as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(rknn_matmul_info_t),
            "::",
            stringify!(reserved)
        )
    );
}
pub type rknn_matmul_info = rknn_matmul_info_t;
extern "C" {
    pub fn rknn_matmul_create(
        ctx: *mut rknn_matmul_ctx,
        info: *mut rknn_matmul_info,
        io_attr: *mut rknn_matmul_io_attr,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_matmul_create_dyn_shape(
        ctx: *mut rknn_matmul_ctx,
        info: *mut rknn_matmul_info,
        shape_num: ::std::os::raw::c_int,
        dynamic_shapes: *mut rknn_matmul_shape,
        io_attrs: *mut rknn_matmul_io_attr,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_matmul_set_io_mem(
        ctx: rknn_matmul_ctx,
        mem: *mut rknn_tensor_mem,
        attr: *mut rknn_matmul_tensor_attr,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_matmul_set_core_mask(
        context: rknn_matmul_ctx,
        core_mask: rknn_core_mask,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_matmul_set_quant_params(
        context: rknn_matmul_ctx,
        params: *mut rknn_quant_params,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_matmul_get_quant_params(
        ctx: rknn_matmul_ctx,
        params: *mut rknn_quant_params,
        scale: *mut f32,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_matmul_set_dynamic_shape(
        ctx: rknn_matmul_ctx,
        shape: *mut rknn_matmul_shape,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_matmul_run(ctx: rknn_matmul_ctx) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_matmul_destroy(ctx: rknn_matmul_ctx) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rknn_B_normal_layout_to_native_layout(
        B_input: *mut ::std::os::raw::c_void,
        B_output: *mut ::std::os::raw::c_void,
        K: ::std::os::raw::c_int,
        N: ::std::os::raw::c_int,
        subN: ::std::os::raw::c_int,
        subK: ::std::os::raw::c_int,
        type_: rknn_matmul_type,
    ) -> ::std::os::raw::c_int;
}
